### PR TITLE
chore: Refactoring inconsistent naming and unnecessary model type

### PR DESCRIPTION
**Pull request by tiopramayudi**
# Description

This PR mainly do refactoring to ml observability related code. Following are the issues:
* Inconsistent field name between `InferenceSchema` and `PyfuncV3Model` `ModelInput` and `ModelOutput`. In `InferenceSchema` unique identifier for each prediction is defined in `row_id_column` where in `ModelInput` and `ModelOutput` are stored in `prediction_ids`. To make the term consistent we will change `prediction_ids` into `row_ids`
* Initially we add new model type when a model wants to onboard to ml observability, but this is necessary user just need to implement `PyfuncV3Model` instead of old `PyFuncModel` and use existing `pyfunc` model type 
* Update documentation on model schema and model observability

# Modifications

* Remove all the code that using `pyfunc_v3` as model type
* `python/sdk/merlin/pyfunc.py` -> Add `row_ids` on `ModelInput` and `ModelOutput`, not remove `prediction_ids` yet to support backward compatibility
# Tests

# Checklist
- [x] Added PR label
- [ ] Added unit test, integration, and/or e2e tests
- [ ] Tested locally
- [x] Updated documentation
- [ ] Update Swagger spec if the PR introduce API changes
- [ ] Regenerated Golang and Python client if the PR introduces API changes

# Release Notes

```release-note

```

### CODE REVIEW

**Comment by leonlnj** [comment]
the PR LGTM, i have some questions

- Pyfunc(v1) all along can have model observability enabled, as long as they use `ModelInput`/`ModelOutput` instead of `dict`
- With this, users using pyfunc(v1) can switch the same model to use mlobs as long as have the above
- Users whom are using pyfuncv3 need to update sdk and code to use pyfuncv1

**Review by leonlnj — APPROVED** [review]
the PR LGTM, i have some questions

Pyfunc(v1) all along can have model observability enabled, as long as they use ModelInput/ModelOutput instead of dict
With this, users using pyfunc(v1) can switch the same model to use mlobs as long as have the above
Users whom are using pyfuncv3 need to update sdk and code to use pyfuncv1

**Comment by tiopramayudi** [comment]
> the PR LGTM, i have some questions
> 
> Pyfunc(v1) all along can have model observability enabled, as long as they use ModelInput/ModelOutput instead of dict With this, users using pyfunc(v1) can switch the same model to use mlobs as long as have the above Users whom are using pyfuncv3 need to update sdk and code to use pyfuncv1



> the PR LGTM, i have some questions
> 
> Pyfunc(v1) all along can have model observability enabled, as long as they use ModelInput/ModelOutput instead of dict With this, users using pyfunc(v1) can switch the same model to use mlobs as long as have the above Users whom are using pyfuncv3 need to update sdk and code to use pyfuncv1

Below is how the relationship before this PR
| Model Type | PyFunc class supported |
|-------------|-------------------------|
| pyfunc          | PyFuncModel, PyFuncV3Model |
| pyfunc_v2 | PyFuncV2Model | 
| pyfunc_v3 | PyFuncModel, PyFuncV3Model |

As you can see the model type `pyfunc` and `pyfunc_v3` basically doesn't have the difference, this PR basically remove model type `pyfunc_v3`. If user want to onboard to model observability the recommended way is to use `pyfunc` model type and implement `PyFuncV3Model`, but as you mentioned user can also implement `PyFuncModel` but returning `PyFuncOutput` on their `infer` function but this is hacky. All of our users that onboard to model observability use `pyfunc` odel type and `PyFuncV3Model` only our integration test that use `pyfunc_v3` model type

**Comment by leonlnj** [comment]
ah thanks, i got it now I thought we were going to remove the Pyfunc class instead. All good, thanks!

**Pull request merged**
